### ISSUE TITLE
Fix importing + rename to 'Import/Export'

### ISSUE THREAD

**Issue by chocolatemelt** [chocolatemelt/padopt#6]
Not working properly (try editing the import text).

Bonus: Add copy button.

**Comment by izenn** [comment]
how is this not working properly?  highlight and delete is how i've been using it, i was going to see if i could make it so everything is automatically selected.

One thing that does need to be fixed is randomize and import/export automatically adds line feeds

**Comment by chocolatemelt** [comment]
If you delete a few entries you won't be able to add entries. Not sure if editing it is really an important feature but as it is it doesn't actually work (at least on my end)

**Comment by izenn** [comment]
i just fixed a couple things that should fix it -- commit 9442680 removes the line feeds (as well as does some other quality of life stuff) that was having javascript put more data in the textarea than was allowed by the textarea maxlength attribute

**Comment by izenn** [comment]
also -- Directly copying to the clipboard via JavaScript is not permitted by any modern browser for security reasons

**Comment by chocolatemelt** [comment]
Oh great. I actually didn't know that but it's also not really an important issue either, closing.
